version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nz01
    ports:
      - "8080:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dz01
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
    links:
      - redis
  db:
    image: postgres:9.5
    container_name: pz01
    ports:
      - '5438:5432'
    environment:
      POSTGRES_ENV_POSTGRES_USER: 'postgres'
      POSTGRES_ENV_POSTGRES_PASSWORD: 'totallysecret'

  redis:
    image: redis:latest
    container_name: rz01
    ports:
     - '6379:6379'
