# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_course_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
